success_build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,7 +18,7 @@ parameters:
   test_deployment:
     type: boolean
     default: false
-  blue_BD:
+  blue_build:
     type: boolean
     default: false
 
@@ -102,34 +102,34 @@ jobs:
             cd BlueApp
             . venv/bin/activate
             make lint
-            exit 1
-      # - run:
-          # name: create docker image
-          # command: |
-            # docker container ls
-            # cd BlueApp
-            # docker build -t blueapp .
-            # docker image ls
-      # - run:
-          # name: test docker image
-          # command: |
-            # cd BlueApp
-            # docker run -d -p 8000:80 blueapp
-            # if docker ps | grep 'blueapp'
-            # then
-              # echo 'Docker works fine'
-            # else
-              # echo 'Docker test failed'
-              # exit 1
-            # fi
-      # - run:
-          # name: upload docker image
-          # command: |
-            # cd BlueApp
-            # echo $docker_password | docker login -u $docker_username --password-stdin 
-            # docker tag blueapp svk100/blueapp
-            # docker container ls
-            # docker push svk100/blueapp
+            # exit 1
+      - run:
+          name: create docker image
+          command: |
+            docker container ls
+            cd BlueApp
+            docker build -t blueapp .
+            docker image ls
+      - run:
+          name: test docker image
+          command: |
+            cd BlueApp
+            docker run -d -p 8000:80 blueapp
+            if docker ps | grep 'blueapp'
+            then
+              echo 'Docker works fine'
+            else
+              echo 'Docker test failed'
+              exit 1
+            fi
+      - run:
+          name: upload docker image
+          command: |
+            cd BlueApp
+            echo $docker_password | docker login -u $docker_username --password-stdin 
+            docker tag blueapp svk100/blueapp
+            docker container ls
+            docker push svk100/blueapp
 
   build-eks-cluster:
     docker:
@@ -176,24 +176,24 @@ jobs:
           name: Install eksctl and kubectl
           command: |
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
-            # curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
-            # chmod +x ./kubectl
-            # sudo mv ./kubectl /usr/local/bin
-            # sudo mv /tmp/eksctl /usr/local/bin
-            # chmod +x /usr/local/bin/kubectl
-            # eksctl version
-            # aws --version
-            # kubectl version --short --client
+            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
+            chmod +x ./kubectl
+            sudo mv ./kubectl /usr/local/bin
+            sudo mv /tmp/eksctl /usr/local/bin
+            chmod +x /usr/local/bin/kubectl
+            eksctl version
+            aws --version
+            kubectl version --short --client
       - run:
           name: Update EKS Cluster
           command: |
             aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name udacity-capstone
             # docker pull svk100/blueapp:latest
             # docker image ls
-            # kubectl apply -f eksConfig/update.yml
-            # kubectl rollout status deployment/udacity-capstone
-            # kubectl rollout history deployment/udacity-capstone
-            # kubectl get rs
+            kubectl apply -f eksConfig/update.yml
+            kubectl rollout status deployment/udacity-capstone
+            kubectl rollout history deployment/udacity-capstone
+            kubectl get rs
 
   test-deployment:
     docker: 
@@ -251,7 +251,7 @@ workflows:
       - test-deployment
 
   Build-Deploy-Blue-workflow:
-    when: << pipeline.parameters.blue_BD >>
+    when: << pipeline.parameters.blue_build >>
     jobs:
       - build-dockerB-image
       - update-eks-cluster:
