test deployment added

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,6 +15,9 @@ parameters:
   build-eks:
     type: boolean
     default: false
+  test_deployment:
+    type: boolean
+    default: false
 
 jobs:
 
@@ -102,7 +105,21 @@ jobs:
             #kubectl get nodes
             kubectl apply -f eksConfig/LBConfig.yml
             kubectl apply -f eksConfig/deployment.yml
-  
+
+  test-deployment:
+    docker: circleci/node:13.8.0
+    steps:
+      - run:
+          name: Test deployment
+          command: |
+            if curl -s http://ad2ba3d2bfd9042899744f3bf32f224b-1144593518.us-east-1.elb.amazonaws.com/ | grep 'This'
+            then
+              echo 'Deployment Successful'
+            else
+              echo 'Deployment Failed'
+              exit 1
+            fi
+    
 workflows:
   build-workflow:
     when: << pipeline.parameters.build >>
@@ -114,3 +131,7 @@ workflows:
     jobs:
       - build-eks-cluster
 
+  test-deployment-workflow:
+    when: << pipeline.parameters.test_deployment >>
+    jobs:
+      - test-deployment
