Updated Proj Files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,26 +1,105 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
+orbs:
+  aws-eks: circleci/aws-eks@1.1.0
+  kubernetes: circleci/kubernetes@1.3.0
+
+parameters:
+  build:
+    type: boolean
+    default: false
+  update:
+    type: boolean
+    default: false
+
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
+
+  build-docker-image:
     docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+      - image: python:3.7.3-stretch
+    steps:
+      - checkout
+      - restore-cache:
+          keys:
+            - v1-dependencies-{{ checksum "requirements.txt" }}
+            # fallback to using the latest cache if no exact match is found
+            - v1-dependencies-
+      - run:
+          name: install dependencies
+          command: |
+            cd GreenApp
+            python3 -m venv venv
+            . venv/bin/activate
+            make install
+            # Install hadolint
+            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
+            chmod +x /bin/hadolint
+      - run:
+          name: run lint
+          command: |
+            cd GreenApp
+            . venv/bin/activate
+            make lint
+      - run:
+          name: create docker image
+          command: |
+            cd GreenApp
+            docker build -t greenapp .
+            docker image ls
+      - run:
+          name: test docker image
+          command: |
+            cd GreenApp
+            docker run -d -p 8000:80 greenapp
+            if curl http://localhost:8000 | grep 'This'
+            then
+              echo 'Docker works fine'
+            else
+              echo 'Docker test failed'
+              exit 1
+            fi
+            
+      - run:
+          name: upload docker image
+          command: |
+            cd GreenApp
+            docker login -u $docker_username -p $docker_password 
+            docker container ls
+            docker push svk100/greenapp
+
+            
+      - save_cache:
+          paths:
+          - ./venv
+          key: v1-dependencies-{{ checksum "requirements.txt" }}
+
+
+
+  build-job:
+    docker:
+      - image: cimg/base:2021.04
     steps:
       - checkout
       - run:
           name: "Say hello"
-          command: "echo Hello, World!"
+          command: echo 'build'
 
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+  update-job:
+    docker:
+      - image: cimg/base:2021.04
+    steps:
+      - checkout
+      - run:
+          name: "Say hello"
+          command: echo 'update'
+  
 workflows:
-  say-hello-workflow:
+  build-workflow:
+    when: << pipeline.parameters.build >>
     jobs:
-      - say-hello
+      - build-job
+ 
+  update-workflow:
+    when: << pipeline.parameters.update >>
+    jobs:
+      - update-job
